using System.CodeDom.Compiler;
using System.Linq;
using Forge.Generators.Common.Models;
using Forge.RoslynShared;
using Microsoft.CodeAnalysis;

namespace Forge.Generators.Common.Emit;

public static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteMultiline(
            """
            // <auto-generated />
            //------------------------------------------------------------------------------
            // This code was automatically generated by Forge Generators.
            //
            // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            //------------------------------------------------------------------------------
            """);
        
        writer.WriteLine();
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }
    
    internal static void EmitGeneratedCodeAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"ForgeGenerators\", \"0.1.0-preview.2\")]");
    }

    internal static void EmitExcludeFromCodeCoverageAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
    }
    
    internal static void EmitTypeDeclarationFromModel(
        TypeDeclModel decl,
        IndentedTextWriter writer,
        string[]? inheritance = null)
    {
        ITypeReferenceModel typeRef = decl.AsTypeRef;
        
        string accessibility = decl.AccessModifier.AsDeclString();
        string isPartial = decl.IsPartial ? "partial " : string.Empty;
        string isSealed = decl.IsSealed && typeRef.TypeKind is not TypeKind.Struct ? "sealed " : string.Empty;
        string isStatic = decl.IsStatic ? "static " : string.Empty;
        
        string typeKeyword = typeRef.TypeKind switch {
            TypeKind.Interface => "interface",
            TypeKind.Struct => typeRef.IsRecord ? "record struct" : "struct",
            TypeKind.Enum => "enum",
            TypeKind.Class => typeRef.IsRecord ? "record" : "class",
            _ => ThrowHelpers.ThrowUnhandledBranch<string>(typeRef.TypeKind)
        };
        
        string typeParams = typeRef.TypeParameters.Length > 0
            ? "<" + string.Join(", ", typeRef.TypeParameters.Select(static tp => tp.FQNGenericBased)) + ">"
            : string.Empty;
        
        string constraints = typeRef.Constraints.Length > 0
            ? string.Join(" ", typeRef.Constraints.Select(static ct => ct.ToString()))
            : string.Empty;

        string inheritFrom = inheritance is not null
            ? string.Join(", ", inheritance)
            : string.Empty;

        string output = $"{accessibility} {isPartial} {isSealed} {isStatic} {typeKeyword} " +
                        $"{decl.TypeNameNoArityNoFQN}{typeParams} " +
                        $"{(!string.IsNullOrEmpty(inheritFrom) ? $": {inheritFrom} " : "")}" +
                        $"{constraints} {{";
        
        writer.WriteLine(output.CollapseRedundantWhitespace());
    }
}