using System;
using System.CodeDom.Compiler;
using System.Linq;
using System.Runtime.CompilerServices;
using Forge.Generators.Common.Models;
using Forge.RoslynShared;
using Microsoft.CodeAnalysis;

namespace Forge.Generators.Common.Emit;

public static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteMultiline(
            """
            // <auto-generated />
            //------------------------------------------------------------------------------
            // This code was automatically generated by Forge Generators.
            //
            // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            //------------------------------------------------------------------------------
            """);
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }
    
    internal static void EmitClassDeclarationFromModel(
        TypeDeclModel decl,
        IndentedTextWriter writer)
    {
        ITypeReferenceModel typeRef = decl.AsTypeRef;
        
        string accessibility = decl.AccessModifier.AsDeclString();
        string isPartial = decl.IsPartial ? "partial " : string.Empty;
        string isSealed = decl.IsSealed ? "sealed " : string.Empty;
        string isStatic = decl.IsStatic ? "static " : string.Empty;

        string typeKeyword = typeRef.TypeKind switch {
            TypeKind.Interface => "interface",
            TypeKind.Struct => typeRef.IsRecord ? "record struct" : "struct",
            TypeKind.Enum => "enum",
            TypeKind.Class => typeRef.IsRecord ? "record" : "class",
            _ => ThrowHelpers.ThrowUnhandledBranch<string>(typeRef.TypeKind)
        };
        
        string typeParams = typeRef.TypeParameters.Length > 0
            ? "<" + string.Join(", ", typeRef.TypeParameters.Select(static tp => tp.FQNGenericBased)) + ">"
            : string.Empty;

        string constraints = typeRef.Constraints.Length > 0
            ? string.Join(" ", typeRef.Constraints.Select(static ct => ct.ToString()))
            : string.Empty;
        
        writer.WriteLine(
            $"{accessibility} {isPartial} {isSealed} {isStatic} {typeKeyword} " +
            $"{decl.TypeNameNoArityNoFQN}{typeParams} " +
            $"{constraints} {{"
        );
        
        writer.Indent++;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static string FQN(Type type) => $"global::{type.FullName}";
}