//HintName: Foo_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo  {
    public  global::System.Int32 xmlParserValue =>  xmlParser;
}
