//HintName: FooT1T2_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo<T1, T2> where T1 : class {
    protected internal  T1 Value1 { set => _value1 = value; }
    
    protected internal  T2 Value2 { set => _value2 = value; }
    
    protected internal  global::System.Lazy<T1> Lazy { set => _lazy = value; }
}
