//HintName: FooT1T2_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo<T1, T2> where T1 : class {
    internal  T1 Value1 {
        get => _value1;
        set => _value1 = value;
    }
    
    internal  T2 Value2 {
        get => _value2;
        set => _value2 = value;
    }
    
    internal  global::System.Lazy<T1> Lazy {
        get => _lazy;
        set => _lazy = value;
    }
}
