//HintName: Foo_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo  {
    private  global::System.Int32 Value { set => _value = value; }
    
    private  global::System.Collections.Generic.Dictionary<global::System.String, global::System.Lazy<global::System.Int32[]>> Dictionary { set => _dictionary = value; }
}
