//HintName: Foo_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo  {
    private protected  global::System.Int32 Value {
        get => _value;
        set => _value = value;
    }
    
    private protected  global::System.Collections.Generic.Dictionary<global::System.String, global::System.Lazy<global::System.Int32[]>> Dictionary {
        get => _dictionary;
        set => _dictionary = value;
    }
}
