//HintName: FooT1T2_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo<T1, T2> where T1 : class {
    private ref readonly T1 Value1 => ref _value1;
    
    private ref readonly T2 Value2 => ref _value2;
    
    private ref readonly global::System.Lazy<T1> Lazy => ref _lazy;
}
