//HintName: FooT1T2_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

[global::System.CodeDom.Compiler.GeneratedCode("ForgeGenerators", "0.1.0-preview.2")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class Foo<T1, T2> where T1 : class {
    private  T1 Value1 { set => _value1 = value; }
    
    private  T2 Value2 { set => _value2 = value; }
    
    private  global::System.Lazy<T1> Lazy { set => _lazy = value; }
}
