//HintName: FooT1T2_AutoProperty.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Forge Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

public partial    class Foo<T1, T2> where T1 : class {
    protected  T1 Value1 =>  _value1;
    
    protected  T2 Value2 =>  _value2;
    
    protected  global::System.Lazy<T1> Lazy =>  _lazy;
}
