name: Release

on:
  push:
    tags: ['v*']
    
# See ref: https://github.com/ImmediatePlatform/Immediate.Handlers/blob/main/.github/workflows/release.yml
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write 
      
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
            
      - name: Restore tools
        run: dotnet tool restore
        
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${GITHUB_REF_NAME#v}

      - name: Test
        run: dotnet test --configuration Release --no-build
        
      - name: Package
        run: dotnet pack -c Release --no-build --property:PackageOutputPath=../../nupkgs -p:Version=${GITHUB_REF_NAME#v}

      - name: Validate Package
        continue-on-error: true
        run: dotnet tool run dotnet-validate -- package local ./nupkgs/*.nupkg
  
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: 7Swaize
          
      - name: NuGet push
        run: >
          dotnet nuget push nupkgs/*.nupkg
          --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          makeLatest: ${{ !contains(github.ref_name, '-') }}